- name: Comment out pipeline archive in fstab
  replace:
    dest: /etc/fstab
    regexp: '^swap.img'
    replace: '#/swap.img'
  tags: update-fstab

- name: swapoff -a
  shell: swapoff -a

- name: remove /etc/containerd/config.toml
  shell: rm /etc/containerd/config.toml

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted

- name: set hostmame
  shell: hostnamectl set-hostname worker-02
